#!/bin/bash

# black
export _color0="#333333"
export _color8="#444444"

# red
export _color1="#ff9c31"
export _color9="#ffc971"

# green
export _color2="#45b69c"
export _color10="#08fbcf"

# yellow
export _color3="#eac435"
export _color11="#fff900"

# blue
export _color4="#0791ad"
export _color12="#54d4ff"

# magenta
export _color5="#9b1a50"
export _color13="#f90086"

# cyan
export _color6="#b60dfc"
export _color14="#ff47da"

# white
export _color7="#616161"
export _color15="#888888"

export _background="#000000"
export _foreground="#ffffff"
export _cursorFG=${_foreground}
export _cursorBG=${_background}
