#!/bin/bash

# black
export _color0="#322922"
export _color8="#67584d"

# red
export _color1="#7a0006"
export _color9="#ba2528"

# green
export _color2="#3d4133"
export _color10="#5d654e"

# yellow
export _color3="#968334"
export _color11="#d2b63b"

# blue
export _color4="#425e90"
export _color12="#7393ce"

# magenta
export _color5="#6f2768"
export _color13="#b65ead"

# cyan
export _color6="#549387"
export _color14="#52ceb7"

# white
export _color7="#b38d6e"
export _color15="#edc09c"

export _background="#210000"
export _foreground="#e1ac7f"
export _cursorFG=${_foreground}
export _cursorBG=${_background}
