#!/bin/sh

NAMEMATCH="\s+|\W+"
TEMPLATE=~/coding/minecraft/plugintemplate/

RED="\e[1;31m"
REDB="\e[41m"

seperator() {
    colorize "black"
    echo "___________________________________________________________________________"
    echo ""
    colorize
}

error() {
    colorize "redb"
    echo "ERROR: $1"
    colorize
}

colorize() {
    if [[ $1 == "" ]]; then
        printf "\e[0m"
    fi

    case  $1  in
        "red") printf "\e[1;31m" ;;
        "green") printf "\e[32m" ;;
        "yellow") printf "\e[1;33m" ;;
        "blue") printf "\e[34m" ;;
        "black") printf "\e[1;30m" ;;
        "redb") printf "\e[41m" ;;
        "greenb") printf "\e[42m" ;;
        "yellowb") printf "\e[43m" ;;
        "blueb") printf "\e[44m" ;;
        "blackb") printf "\e[40m" ;;
        *)
    esac
}

PROJECTNAME=$1
PACKAGENAME=${1,,}

if [[ $USER != "menfie" ]]; then
    error "this script can only be ran by the menfie account. please no root or anything else"
    exit
elif [[ $1 == "" || -z PROJECTNAME || $1 =~ $NAMEMATCH ]]; then
    error "usage: newplugin <projectname> <options>"
    exit
fi

echo "creating a new spigot plugin project with the name '$PROJECTNAME' and
the package name '$PACKAGENAME'"
seperator

sleep 1s

CPLOC=$TEMPLATE../$PACKAGENAME

if [[ -a $CPLOC ]]; then
    error "a project with the same name already exists!"
    exit
fi

colorize "blue"

echo "> cloning the template"
cp -r $TEMPLATE $CPLOC

echo "> changing the working directory to '$CPLOC'"
cd $CPLOC

echo "> replacing all the 'PluginName's with '$PROJECTNAME'"
sed -i "s/PluginName/$PROJECTNAME/g" build.gradle settings.gradle src/main/resources/plugin.yml src/main/java/me/blackness/pluginname/PluginName.java

echo "> replacing all the 'pluginname's with '$PACKAGENAME'"
sed -i "s/pluginname/$PACKAGENAME/g" build.gradle settings.gradle src/main/resources/plugin.yml src/main/java/me/blackness/pluginname/PluginName.java

echo "> changing the working directory to 'src/main/java/me/blackness'"
cd src/main/java/me/blackness/

echo "> renaming 'pluginname/PluginName.java' as 'pluginname/$PROJECTNAME.java'"
mv pluginname/PluginName.java pluginname/$PROJECTNAME.java

echo "> renaming 'pluginname' as '$PACKAGENAME'"
mv pluginname $PACKAGENAME

echo ""
colorize "green"
echo "the project is created!"
