#!/bin/sh

select="false"
test "$1" = "-s" && select="true"

mkdir -p "$HOME/Screenshots"

number="$(ls -1 $HOME/Screenshots | cut -d'.' -f1 | sort -n | tail -n 1)"
number="$(( number + 1 ))"

opts=""
test "$select" = "true" && opts="-s"

sleep 0.45
scrot $opts "$HOME/Screenshots/${number}.png"

notify-send -t 2000 "Screenshot taken"
